### ISSUE TITLE
Cannot run bots from VPS due to SSL error

### ISSUE THREAD

**Issue by freaky767** [GeniusXD/free-agario-fb-bots#7]
error:
`Mixed Content: The page at 'https://agar.io/#MN433N' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://x.x.x.x:8083/'. This request has been blocked; this endpoint must be available over WSS.`

`Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`

**Comment by ItsDavehere** [comment]
I have the same problems did you fix it yet ?

**Comment by freaky767** [comment]
nope, the only way i think to fix it is by introducing an SSL certificate to the server, which would require more coding, then you could connect to the VPS using secure websockets ( im not a good coder )

**Comment by ItsDavehere** [comment]
I tried everything it never worked for me either

**Comment by ItsDavehere** [comment]
@freaky767 hello I found how it works it's pretty easy add me on discord I will tell you đᗩƔĕ#2874

**Comment by freaky767** [comment]
make a pull request or fork project and add commits please!

**Comment by ItsDavehere** [comment]
@freaky767 you don't that all you need is go to chrome://settings/content/insecureContent -----> allow agar.io so now agario can connect to your server without wss you can use ws tried and worked

**Comment by ArvdSrh** [comment]
Hey bro,

Sorry for replying this late, I was quite busy recently. Yes, you can use the insecureContent method in your browser's settings or get an SSL certificate for your VPS which is also quite easy. But, the **bots are patched** now.

Cheers ;)
