### ISSUE TITLE
Facebook Tokens not working

### ISSUE THREAD

**Issue by RoOuFX** [GeniusXD/free-agario-fb-bots#8]
I have 150 fb tokens to use, and i'm using it.
![image](https://user-images.githubusercontent.com/55519886/104108517-0b24b000-52a4-11eb-914c-e73288a1196d.png)

But when i start the bots it only start with 10 mass bots, and every thing is fine with archives, but fb bots dont connect, can someone tell me how to fix or whats the problem? 

![image](https://user-images.githubusercontent.com/55519886/104108512-03650b80-52a4-11eb-9b90-e2d68d2616ef.png)

**Comment by ghost** [comment]
I think your facebook account is banned

**Comment by ArvdSrh** [comment]
Hey bro,

All facebook files are connected to one of our own servers. We have closed the server to save cost because the bots are no longer spawning in big amount. Sorry for replying this late, hope this helps you.
**Bots are patched**

Cheers,
Genius
